// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFF-YJHpXMtDAmfz2aGLdqRSVEbOkSobA',
    appId: '1:153326572689:web:70c65a621bad127a435b30',
    messagingSenderId: '153326572689',
    projectId: 'social-app-2358c',
    authDomain: 'social-app-2358c.firebaseapp.com',
    storageBucket: 'social-app-2358c.appspot.com',
    measurementId: 'G-VPMWS6HXLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHEExx5t0LC8bxFitjrzG0r4iPoWXFY7w',
    appId: '1:153326572689:android:ac5afa3e77013fa5435b30',
    messagingSenderId: '153326572689',
    projectId: 'social-app-2358c',
    storageBucket: 'social-app-2358c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL7-5qMklb26elmPFbYLm6qm9E255tDYw',
    appId: '1:153326572689:ios:cbbdb9b75aaf2de2435b30',
    messagingSenderId: '153326572689',
    projectId: 'social-app-2358c',
    storageBucket: 'social-app-2358c.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL7-5qMklb26elmPFbYLm6qm9E255tDYw',
    appId: '1:153326572689:ios:cbbdb9b75aaf2de2435b30',
    messagingSenderId: '153326572689',
    projectId: 'social-app-2358c',
    storageBucket: 'social-app-2358c.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFF-YJHpXMtDAmfz2aGLdqRSVEbOkSobA',
    appId: '1:153326572689:web:644c5f09b1793bc3435b30',
    messagingSenderId: '153326572689',
    projectId: 'social-app-2358c',
    authDomain: 'social-app-2358c.firebaseapp.com',
    storageBucket: 'social-app-2358c.appspot.com',
    measurementId: 'G-S2RTS7VYGG',
  );
}
